### ISSUE TITLE
Tool asks for code list name but uses generic file names and overwrites existing code lists

### ISSUE THREAD

**Issue by ts2108** [rw251/code-list-creator#10]
Output is saved to the out folder using generic file names and code list name is not utilised

**Comment by rw251** [comment]
The code list name is stored in the metadata file which could be used by other pieces of software - however you're right about the output being overridden - this shouldn't happen - at least not without some sort of warning.

**Comment by rw251** [comment]
Fixed - will be available in release 1.1.0.
