### ISSUE TITLE
Error using special characters '

### ISSUE THREAD

**Issue by rc16** [rw251/code-list-creator#6]
this error appeared when I used the search term felty's:
`
{ Error: SQLITE_ERROR: near "s": syntax error
    at Error (native) errno: 1, code: 'SQLITE_ERROR' }
No matching terms found in the dictionary
Code list written to out/codes.txt
Metadata written to out/meta.json
`

**Comment by rw251** [comment]
Good spot. I'll investigate.

**Comment by rw251** [comment]
Fixed - will be available in release 1.1.0.
